finish contact form
Frederick-Ye/portfolio-project pull request #7
Opened 2023-11-25 15:54 UTC by Frederick-Ye

2023-11-27 13:54 UTC, rex-9 requested changes
## STATUS: REQUIRES CHANGES 🚦 ⚠️ ♻️ 

Hi 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![close lady](https://user-images.githubusercontent.com/99246359/204822829-8d2e1877-0db5-435f-9e1e-438a33fc65d7.gif)

## Highlights 💯 
- Great design and UI ❌ 
- No Linter errors ✔️
- Descriptive Pull request summary✔️
- Good commit messages ✔️
- Professional Readme file ✔️ 

## Required Changes ♻️
- I believe the following are not the expected UI of the project. Please fix them according to the proper figma design. And Please close duplicate Pull Requests. You only need one Pull Request for one Project.

<img width="1440" alt="image" src="https://github.com/Frederick-Ye/portfolio-project/assets/77402992/497763fd-4164-4982-a50b-a0b9a2b399b6">

<img width="1440" alt="image" src="https://github.com/Frederick-Ye/portfolio-project/assets/77402992/761288da-9e9d-4426-9a98-97048b7dfdc2">

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-11-27 15:03 UTC, Frederick-Ye commented
Thanks for the review Bro Htet Naing @rex-9 . The reason why the UI isn't working is that i only build it for mobile-version 375px. Please inspect with 375px width. I will fix for desktop version in the next project.

2023-11-28 15:31 UTC, rex-9 approved these changes

2023-11-28 15:32 UTC, rex-9 commented
Good Job @Frederick-Ye , only one thing to fix. Prevent the screen from horizontal scroll. Please fix that in the next project. I'll just approve it for now.

2023-11-29 02:16 UTC, closed without merging